<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-25T13:57:12 CLT" name="Sample Test Suite" finished-at="2023-08-25T13:58:02 CLT" duration-ms="49381">
    <groups>
    </groups>
    <test started-at="2023-08-25T13:57:12 CLT" name="Clase Automation QA" finished-at="2023-08-25T13:58:02 CLT" duration-ms="49381">
      <class name="test.java.carritocompras.CarritoComprasTest">
        <test-method is-config="true" signature="beforeTestMethod()[pri:0, instance:test.java.carritocompras.CarritoComprasTest@790da477]" started-at="2023-08-25T13:57:12 CLT" name="beforeTestMethod" finished-at="2023-08-25T13:57:12 CLT" duration-ms="104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestMethod -->
        <test-method is-config="true" signature="beforeMethodMethod(java.lang.String,java.lang.reflect.Method)[pri:0, instance:test.java.carritocompras.CarritoComprasTest@790da477]" started-at="2023-08-25T13:57:12 CLT" name="beforeMethodMethod" finished-at="2023-08-25T13:57:16 CLT" duration-ms="3864" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.carritocompras.CarritoComprasTest.QAS12(java.lang.String[]) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodMethod -->
        <test-method signature="QAS12([Ljava.lang.String;)[pri:0, instance:test.java.carritocompras.CarritoComprasTest@790da477]" started-at="2023-08-25T13:57:16 CLT" name="QAS12" data-provider="carritoComprasData" finished-at="2023-08-25T13:58:02 CLT" duration-ms="45157" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@550de6b8]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at main.java.utils.Utils.eventFailed(Utils.java:43)
at main.java.pageEvents.LoginEvents.iniciarSesion(LoginEvents.java:60)
at test.java.carritocompras.CarritoComprasTest.QAS12(CarritoComprasTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QAS12 -->
        <test-method is-config="true" signature="afterMethodMethod(org.testng.ITestResult)[pri:0, instance:test.java.carritocompras.CarritoComprasTest@790da477]" started-at="2023-08-25T13:58:02 CLT" name="afterMethodMethod" finished-at="2023-08-25T13:58:02 CLT" duration-ms="78" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=QAS12 status=FAILURE method=CarritoComprasTest.QAS12([Ljava.lang.String;)[pri:0, instance:test.java.carritocompras.CarritoComprasTest@790da477] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodMethod -->
        <test-method is-config="true" signature="afterTestMethod()[pri:0, instance:test.java.carritocompras.CarritoComprasTest@790da477]" started-at="2023-08-25T13:58:02 CLT" name="afterTestMethod" finished-at="2023-08-25T13:58:02 CLT" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestMethod -->
      </class> <!-- test.java.carritocompras.CarritoComprasTest -->
    </test> <!-- Clase Automation QA -->
  </suite> <!-- Sample Test Suite -->
</testng-results>
